name: range-diff

on:
  pull_request:
    types: [synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  range-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: svenvanheugten/gh-post-range-diff@v0.4.2
